In [48]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
print("Libraries imported")

Libraries imported


In [50]:
inputs = [1, 2, 3, 2.5]
weights1 = [0.2, 0.8, -0.5, 1.0]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]
bias1 = 2.0
bias2 = 3
bias3 = 0.5

In [51]:
output = [
    inputs[0] * weights1[0] + inputs[1] * weights1[1] + inputs[2] * weights1[2] + inputs[3] * weights1[3] + bias1,
    inputs[0] * weights2[0] + inputs[1] * weights2[1] + inputs[2] * weights2[2] + inputs[3] * weights2[3] + bias2,
    inputs[0] * weights3[0] + inputs[1] * weights3[1] + inputs[2] * weights3[2] + inputs[3] * weights3[3] + bias3
]

In [52]:
print(output)

[4.8, 1.21, 2.385]


In [53]:
inputs = [1, 2, 3, 2.5]
weights =  [[0.2, 0.8, -0.5, 1.0],
            [0.5, -0.91, 0.26, -0.5], 
            [-0.26, -0.27, 0.17, 0.87]]
biases = [2, 3, 0.5]

In [54]:
# Output of current layer
layer_outputs = []

# For each neuron
for neurons_weights, neuron_bias in zip(weights, biases):
    # Zero output of given neuron
    neuron_output = 0
    # For each input and weight to the neuron
    for n_inputs, weight in zip(inputs, neurons_weights):
        #multiply by associated weight and add to the neurons output variable
        neuron_output += n_inputs*weight
    # adding bias
    neuron_output += neuron_bias

    #put neurons back into result
    layer_outputs.append(neuron_output)

In [55]:
print(layer_outputs)

[4.8, 1.21, 2.385]


In [56]:
#3 Dimensional array (3,2,4)
lolol = [[[1,2,3,4],
          [2,3,4,5]],
          [[4,5,6,7],
          [2,3,5,6]],
          [[1,3,5,7],
           [2,5,7,8]]
           ]

In [86]:
#Single Neuron with Numpy
inputs = [1, 2, 3, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0

In [87]:
outputs = np.dot(inputs, weights) + bias
outputs

np.float64(4.8)

In [62]:
#A Layer of Neurons with Numpy
inputs = [1, 2, 3, 2.5]
weights =  [[0.2, 0.8, -0.5, 1.0],
            [0.5, -0.91, 0.26, -0.5], 
            [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

In [63]:
outputs = np.dot(weights, inputs) + bias
outputs

array([4.8  , 0.21 , 3.885])

In [68]:
a = [1,2,3]
b = [2,3,4]
a = np.array([a])
b = np.array([b]).T

np.dot(a,b)

array([[20]])

In [76]:
#A layer of Neurons & batches of Data w/Numpy
inputs = [[1.0, 2.0, 3.0, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]
weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]
outputs = np.dot(inputs, np.array(weights).T)+biases

In [77]:
outputs

array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])