In [1]:
import numpy as np

In [15]:
layer_outputs = [4.8, 1.21, 2.385]
#First step is to "exponentiate" the outputs-Euler's number e, E to match common coding
E = 2.71828182846

# for each value in a vector, calculate the exponential value

exp_values = []
for output in layer_outputs:
    exp_values.append(E**output)
exp_values

[121.51041751893969, 3.3534846525504487, 10.85906266492961]

In [16]:
# sum of exponentiated values
sUm = sum(exp_values)
# Sij or normalized values
Sij = []
for i in exp_values:
    Sij.append(i/sUm)

In [17]:
norm_values = Sij
print(f"Normalised values: {norm_values}")
print(f"Sum of Normalized values: {sum(norm_values)}")

Normalised values: [0.8952826639573506, 0.024708306782070668, 0.08000902926057876]
Sum of Normalized values: 1.0


In [18]:
# Numpy way
layer_outputs = [4.8, 1.21, 2.385]
exp_values = np.exp(layer_outputs)
print(f"Exponentiated values: {exp_values}")

#normalized values
norm_values = exp_values / np.sum(exp_values)
print(f"Normalised values: {norm_values}")
print(f"Sum of Normalized values: {np.sum(norm_values)}")

Exponentiated values: [121.51041752   3.35348465  10.85906266]
Normalised values: [0.89528266 0.02470831 0.08000903]
Sum of Normalized values: 0.9999999999999999


In [28]:
# Get unnormalized probabilities
exp_values = np.exp(norm_values)
probablities = exp_values / np.sum(layer_outputs, axis=None, keepdims=True)

In [26]:
probablities

array([0.29160544, 0.1220984 , 0.12904072])

In [34]:
np.sum(layer_outputs, axis=0, keepdims=True)

array([8.395])

In [ ]:
#Softmax Activation
class Activation_Softmax:
    # Forward pass
    def forward(self, inputs):
        # Get unnormalized probabilities
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))

        # Normalize them for each sample
        probablities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        self.output = probablities

In [36]:
softmax = Activation_Softmax()
softmax.forward([[1,2,3]])
print(softmax.output)

[[0.09003057 0.24472847 0.66524096]]


In [1]:
from nnfs.datasets import spiral_data
X, y = spiral_data(samples=100, classes=3)
