In [18]:
x = [1.0, -2.0, 3.0] #input values
w = [-3.0, -1.0, 2.0] #weights
b = 1.0 # bias

xw0 = x[0] * w[0]
xw1 = x[1] * w[1]
xw2 = x[2] * w[2]
print(xw0, xw1, xw2)

-3.0 2.0 6.0


In [19]:
z = xw0 + xw1 + xw2 + b 
z

6.0

In [20]:
y = max(z,0) #ReLU activation function
y

6.0

In [21]:
dvalue = 1.0 # since the output here is 6 it's derivative is 1 for this example
drelu_dz = dvalue * (1. if z>0 else 0.)
drelu_dz

1.0

In [22]:
dsum_dxw0 = 1 # partial derivative of x respect to the x input weight for 0th pair of inputs and weight
drelu_dxw0 = drelu_dz * dsum_dxw0
drelu_dxw0

1.0

In [23]:
dsum_dxw1 = 1 # partial derivative of x respect to the x input weight for 0th pair of inputs and weight
drelu_dxw1 = drelu_dz * dsum_dxw1
drelu_dxw1

1.0

In [24]:
dsum_dxw2 = 1 # partial derivative of x respect to the x input weight for 0th pair of inputs and weight
drelu_dxw2 = drelu_dz * dsum_dxw2
drelu_dxw2

1.0

In [25]:

dsum_db = 1 # biases 
drelu_db = drelu_dz * dsum_db
drelu_db

1.0

In [26]:
# Back propagation/derivative of ReLU(sum(wx+b))
# where ReLU 0 or 1
# (drelu/dsum) * (dsum/dxw and b also) * (dxw/dx and dxw/dw(partial derivative))

In [27]:
dmul_dx0 = w[0]
dmul_dw0 = x[0]
drelu_dx0 = drelu_dxw0 * dmul_dx0
drelu_dw0 = drelu_dxw0 * dmul_dw0
drelu_dx0

-3.0

In [28]:
dmul_dx1 = w[1]
dmul_dw1 = x[1]
drelu_dx1 = drelu_dxw1 * dmul_dx1
drelu_dw1 = drelu_dxw1 * dmul_dw1
drelu_dx1

-1.0

In [29]:
dmul_dx2 = w[2]
dmul_dw2 = x[2]
drelu_dx2 = drelu_dxw2 * dmul_dx2
drelu_dw2 = drelu_dxw2 * dmul_dw2
drelu_dx2

2.0

In [30]:
print(drelu_dx0, drelu_dw0, drelu_dx1, drelu_dw1, drelu_dx2, drelu_dw2)

-3.0 1.0 -1.0 -2.0 2.0 3.0


In [33]:
drelu_dx0 = dvalue * (1. if z > 0 else 0.) * w[0]
drelu_dx1 = dvalue * (1. if z > 0 else 0.) * w[1]
drelu_dx2 = dvalue * (1. if z > 0 else 0.) * w[2]
print(drelu_dx0, drelu_dx1, drelu_dx2)

-3.0 -1.0 2.0


In [ ]:
dx = [drelu_dx0, drelu_dx1, drelu_dx2] # gradients on inputs
dw = [drelu_dw0, drelu_dw1, drelu_dw2] # gradients on weights
db = drelu_db # gradient on bias... just 1 bias here

In [35]:
print(w, b)

[-3.0, -1.0, 2.0] 1.0


In [37]:
w[0] += -0.001 * dw[0]
w[1] += -0.001 * dw[1]
w[2] += -0.001 * dw[2]
b += -0.001 * db

In [38]:
print(w,b)

[-3.002, -0.996, 1.9940000000000002] 0.999


In [39]:
xw0 = x[0] * w[0]
xw1 = x[1] * w[1]
xw2 = x[2] * w[2]
z = xw0 + xw1 +xw2 +b
y = max(z,0)
print(y)

5.971000000000001


In [7]:
import numpy as np
# Passed in gradient from the next layer
# for the purpose of this example we're going to use a vector of 1s
dvalues = np.array([[1., 1., 1.],
                    [2., 2., 2.],
                    [3., 3., 3.]])

In [20]:
# we have 3 sets of weights - one set for each neurons
# we have 4 inputs, thus 4 weights
# weights transposed
weights = np.array([[0.2, 0.8, -0.5, 1],
                    [0.5, -0.91, 0.26, -0.5],
                    [-0.26, -0.27, 0.17, 0.87]]).T

# sum weights of given input
# & multiply by passed in gradient for this neuron
dx0 = sum(weights[0]*dvalues[0])
dx1 = sum(weights[1]*dvalues[0])
dx2 = sum(weights[2]*dvalues[0])
dx3 = sum(weights[3]*dvalues[0])
dinputs = np.array([dx0, dx1, dx2 ,dx3])
print(dinputs)

[ 0.44 -0.38 -0.07  1.37]


In [11]:
# or just
dinputs = np.dot(dvalues[0], weights.T)
print(dinputs)

[ 0.44 -0.38 -0.07  1.37]


In [14]:
inputs = np.array([[1, 2, 3, 2.5],
                   [2., 5., -1., 2],
                   [-1.5, 2.7, 3.3, -0.8]])

In [15]:
dinputs = np.dot(dvalues, weights.T)
print(dinputs)

[[ 0.44 -0.38 -0.07  1.37]
 [ 0.88 -0.76 -0.14  2.74]
 [ 1.32 -1.14 -0.21  4.11]]


In [17]:
dweights = np.dot(inputs.T, dvalues)
print(dweights)

[[ 0.5  0.5  0.5]
 [20.1 20.1 20.1]
 [10.9 10.9 10.9]
 [ 4.1  4.1  4.1]]


In [18]:
biases = np.array([[2, 3, 0.5]])

In [19]:
dbiases = np.sum(dvalues, axis=0, keepdims=True)
print(dbiases)

[[6. 6. 6.]]


In [22]:
z = np.array([[1, 2, -3, -4],
              [2, -7, -1, 3],
              [-1, 2, 5, -1]])
dvalues = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])
# ReLU activation's derivative
drelu = np.zeros_like(z)
drelu[z > 0] = 1
print(drelu)
 
# The chain rule
drelu *= dvalues
print(drelu)

[[1 1 0 0]
 [1 0 0 1]
 [0 1 1 0]]
[[ 1  2  0  0]
 [ 5  0  0  8]
 [ 0 10 11  0]]


In [23]:
drelu = dvalues.copy()
drelu[z <=0 ] = 0
print(drelu)

[[ 1  2  0  0]
 [ 5  0  0  8]
 [ 0 10 11  0]]
