In [1]:
import numpy as np

In [15]:
layer_outputs = [4.8, 1.21, 2.385]
#First step is to "exponentiate" the outputs-Euler's number e, E to match common coding
E = 2.71828182846

# for each value in a vector, calculate the exponential value

exp_values = []
for output in layer_outputs:
    exp_values.append(E**output)
exp_values

[121.51041751893969, 3.3534846525504487, 10.85906266492961]

In [16]:
# sum of exponentiated values
sUm = sum(exp_values)
# Sij or normalized values
Sij = []
for i in exp_values:
    Sij.append(i/sUm)

In [17]:
norm_values = Sij
print(f"Normalised values: {norm_values}")
print(f"Sum of Normalized values: {sum(norm_values)}")

Normalised values: [0.8952826639573506, 0.024708306782070668, 0.08000902926057876]
Sum of Normalized values: 1.0


In [18]:
# Numpy way
layer_outputs = [4.8, 1.21, 2.385]
exp_values = np.exp(layer_outputs)
print(f"Exponentiated values: {exp_values}")

#normalized values
norm_values = exp_values / np.sum(exp_values)
print(f"Normalised values: {norm_values}")
print(f"Sum of Normalized values: {np.sum(norm_values)}")

Exponentiated values: [121.51041752   3.35348465  10.85906266]
Normalised values: [0.89528266 0.02470831 0.08000903]
Sum of Normalized values: 0.9999999999999999


In [28]:
# Get unnormalized probabilities
exp_values = np.exp(norm_values)
probablities = exp_values / np.sum(layer_outputs, axis=None, keepdims=True)

In [26]:
probablities

array([0.29160544, 0.1220984 , 0.12904072])

In [34]:
np.sum(layer_outputs, axis=0, keepdims=True)

array([8.395])

In [ ]:
#Softmax Activation
class Activation_Softmax:
    # Forward pass
    def forward(self, inputs):
        # Get unnormalized probabilities
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))

        # Normalize them for each sample
        probablities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        self.output = probablities

In [36]:
softmax = Activation_Softmax()
softmax.forward([[1,2,3]])
print(softmax.output)

[[0.09003057 0.24472847 0.66524096]]


In [1]:
from nnfs.datasets import spiral_data
X, y = spiral_data(samples=100, classes=3)


In [ ]:
import matplotlib.pyplot as plt

iterations = list(range(1, 11))  # 10 iterations for example
# Loss values for 3 learning rates (simulated)
loss_lr_small = [10, 9, 8, 7.5, 7, 6.5, 6.2, 6, 5.8, 5.7]    # slow
loss_lr_medium = [10, 7, 4, 2.5, 1.5, 0.8, 0.4, 0.2, 0.1, 0.05] # fast
loss_lr_large = [10, 12, 15, 14, 16, 18, 20, 25, 30, 35]        # diverging

plt.plot(iterations, loss_lr_small, label='lr=0.001 (slow)')
plt.plot(iterations, loss_lr_medium, label='lr=0.01 (fast)')
plt.plot(iterations, loss_lr_large, label='lr=0.1 (diverges)')

plt.xlabel('Iterations')
plt.ylabel('Loss')
plt.title('Gradient Descent Convergence for Different Learning Rates')
plt.legend()
plt.show()

In [ ]:
learning_rates = ['0.001', '0.01', '0.1']
iterations_to_converge = [10, 6, 0]  # 0 = never converges

plt.bar(learning_rates, iterations_to_converge, color=['blue', 'green', 'red'])
plt.ylabel('Iterations to Converge')
plt.title('Convergence Comparison')
plt.show()

In [2]:
class Loss:
    def calculate(self, output, y):
        # calculate sample loss
        sample_loss = self.forward(output, y)
        # calculate mean loss
        data_loss = np.mean(sample_loss)
        return data_loss